### ISSUE TITLE
Add tests for this gem

### ISSUE THREAD

**Issue by wimnorder** [Smolget/vscale-api#23]

**Comment by Shalmezad** [comment]
@wimnorder Would something like this:
https://github.com/Shalmezad/vscale-api/tree/spec_tests
suite your needs? (still have a bunch of tests to write, but want to make sure it fits what you want)

**Comment by wimnorder** [comment]
@Shalmezad Yes, the code of specs look good and very clean! 👍 Thank you for your participation!

**Comment by Shalmezad** [comment]
A slight warning about the houndci-bot would've been nice. 😐 
Anyways, specs for the API endpoints in the gem is in pull request #24. 

Separate of this, may want to take a look at scalet_sshkeys: https://github.com/Smolget/vscale-api/blob/master/lib/vscale/api/servers.rb#L39 as it probably needs to be tweaked (left a spec for it commented).

**Comment by Shalmezad** [comment]
Fixed most of the warnings in my last commit. Only one left is "Missing frozen string literal comment." for:
```
require 'spec_helper'
```

It's a fairly simple fix (`require 'spec_helper'.freeze`), but up to you on whether you feel it necessary, considering the code base does not follow this lint check.

**Comment by wimnorder** [comment]
Thank you @Shalmezad 👍 

PS: Sorry about hound, i forgot about that, i'll include information to readme 😉
